services:
  db:
    image: postgres:15
    restart: always
    container_name: participium_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  test_db:
    image: postgres:15
    restart: always
    container_name: participium_test_db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data

  participium:
    image: skeitt/participium-team-4:latest
    container_name: participium
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  telegram_bot:
    image: skeitt/participium-team-4-bot:latest
    container_name: participium_bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - participium
volumes:
  pgdata:
  pgdata_test:
