services:
  db:
    image: postgres:15
    restart: always
    container_name: participium_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: participium_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  test_db:
    image: postgres:15
    restart: always
    container_name: participium_test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: participium_test_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data

  participium:
    image: andrea334214/participium:latest
    container_name: participium
    ports:
      - "3000:3000"
    environment:
      NEXTAUTH_SECRET: "team4SuperImportantSecretCarefullyManaged"
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/participium_db"
      NODE_ENV: production
      SKIP_INIT: "true"
    depends_on:
      - db


  telegram_bot:
    image: andrea334214/participium_bot:latest
    container_name: participium_bot
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/participium_db"
      BOT_TOKEN: "${BOT_TOKEN}"
    depends_on:
      - participium
volumes:
  pgdata:
  pgdata_test:
