services:
  db:
    image: postgres:15
    restart: always
    container_name: participium_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: participium_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  test_db:
    image: postgres:15
    restart: always
    container_name: participium_test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: participium_test_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data

  participium:
    build:
      context: ./participium
      dockerfile: Dockerfile
      args:
        DATABASE_URL: "postgresql://postgres:postgres@db:5432/participium_db"
    image: skeitt/participium-team-4:latest
    platform: linux/amd64
    container_name: participium
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - ./participium/.env
    environment:
      NODE_ENV: production
      SKIP_INIT: "true"
    depends_on:
      - db


  telegram_bot:
    build:
      context: ./bot   
    image: skeitt/participium-team-4-bot:latest
    platform: linux/amd64
    container_name: participium_bot
    restart: unless-stopped
    env_file:
      - ./bot/.env
    depends_on:
      - participium
volumes:
  pgdata:
  pgdata_test:
