services:
  db:
    image: postgres:15
    restart: always
    container_name: participium_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: participium_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  test_db:
    image: postgres:15
    restart: always
    container_name: participium_test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: participium_test_db
    ports:
      - "5433:5432" 
    volumes:
      - pgdata_test:/var/lib/postgresql/data
volumes:
  pgdata:
  pgdata_test: